services:
  - type: web
    name: financial-portfolio
    env: node
    buildCommand: |
      cd frontend && \
      npm install -g serve && \
      npm install && \
      npm run build
    startCommand: serve -s build -l $PORT
    staticPublish: frontend/build/
